In [1]:
import numpy as np
import pandas as pd

import joblib

In [2]:
x = joblib.load('essay_laser_asap7_prompt_whole_paragraph')
x = np.array(x)
x.shape

(1570, 1024)

In [4]:
x

array([[ 1.83901470e-02, -1.36286235e-05,  5.31674549e-03, ...,
         8.18793569e-03,  3.13197784e-02,  9.55824926e-03],
       [ 1.88276190e-02,  3.74422735e-03,  5.80948964e-03, ...,
        -4.91313403e-04,  1.79005824e-02,  1.79077704e-02],
       [ 3.30975349e-03, -2.11523729e-05,  1.02802590e-02, ...,
        -1.05668872e-03,  2.14381069e-02,  1.24892769e-02],
       ...,
       [ 9.12649278e-03, -1.92564821e-05,  1.05632767e-02, ...,
         1.66696180e-02,  1.02144042e-02,  1.86037030e-02],
       [ 1.04480255e-02,  8.60674400e-03,  7.21330289e-03, ...,
         1.32011697e-02,  1.18104974e-02, -1.91768806e-03],
       [ 1.40916826e-02,  1.75504736e-03, -1.81743206e-04, ...,
         1.13222962e-02,  3.32022719e-02,  1.97179485e-02]], dtype=float32)

In [5]:
x[-2:]

array([[ 0.01044803,  0.00860674,  0.0072133 , ...,  0.01320117,
         0.0118105 , -0.00191769],
       [ 0.01409168,  0.00175505, -0.00018174, ...,  0.0113223 ,
         0.03320227,  0.01971795]], dtype=float32)

In [4]:
x = x[:-1,:]
x.shape

(1569, 1024)

In [5]:
x[-1]

array([ 0.01044803,  0.00860674,  0.0072133 , ...,  0.01320117,
        0.0118105 , -0.00191769], dtype=float32)

In [6]:
joblib.dump(x, 'essay_laser_whole_asap7')

['essay_laser_whole_asap7']