In [6]:
!pip install krippendorff

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [7]:
!pip install pyagree

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [21]:
import joblib
import matplotlib.pyplot as plt
#from quadratic_weighted_kappa_edit import quadratic_weighted_kappa, onehalf_weighted_kappa, weighted_matrix, onehalf_weighted_matrix, linear_weighted_kappa
import numpy as np
from sklearn.metrics import cohen_kappa_score, confusion_matrix, ConfusionMatrixDisplay
import krippendorff
from pyagree import bangdiwala_b, scott_pi

## Reversing Confusion Matrix to Array of ratings

In [22]:
def extract_array_from_cm(cm, k):
    r1 = []
    r2 = []
    for i in range(len(cm)):
        for j in range(len(cm[i])):
            if i == j:       
                for x in range(cm[i][j]):
                    r1.extend([k[i]])
                    r2.extend([k[j]])
            else:
                for x in range(cm[i][j]):            
                    r1.extend([k[i]])                
                    r2.extend([k[j]])
    return r1, r2

## Create Confusion Matrix

In [23]:
ConfMatrix = np.array([[17,5,4,1],[4,14,3,4],[5,2,13,3],[2,4,3,16]])
ConfMatrix

array([[17,  5,  4,  1],
       [ 4, 14,  3,  4],
       [ 5,  2, 13,  3],
       [ 2,  4,  3, 16]])

In [25]:
k = [1,2,3,4]
r1, r2 = extract_array_from_cm(ConfMatrix, k)

In [26]:
print(r1)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


In [27]:
print(r2)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]


## Cohen's Kappa

In [28]:
cohen_kappa_score(r1,r2)

0.46595460614152207

## Linear Weighted Kappa

In [29]:
cohen_kappa_score(r1, r2, weights='linear')

0.5029977911012937

## Quadratic Weighted Kappa

In [30]:
cohen_kappa_score(r1, r2, weights='quadratic')

0.5532939714108143

## Prepare array format for Scott's Pi, Bangdiwala's B, and Krippendorff's alpha

In [109]:
r1_ = np.array(r1).reshape(1,-1)
r2_ = np.array(r2).reshape(1,-1)

r = np.concatenate((r1_,r2_), axis=0)
r

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

## Scott's Pi

In [116]:
scott_pi(np.matrix(ConfMatrix))

0.46591895320114823

## Bangdiwala's B

In [111]:
bangdiwala_b(ConfMatrix)

0.48464619492656874

## Krippendorff's alpha

In [112]:
krippendorff.alpha(r)

0.5476563724721744

In [45]:
def weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            weighted[i][j] = float(((i-j)**2)/(N-1)**2) 
    return weighted

In [46]:
weighted_matrix(3)

array([[0.  , 0.25, 1.  ],
       [0.25, 0.  , 0.25],
       [1.  , 0.25, 0.  ]])

In [47]:
weighted_matrix(4)

array([[0.        , 0.11111111, 0.44444444, 1.        ],
       [0.11111111, 0.        , 0.11111111, 0.44444444],
       [0.44444444, 0.11111111, 0.        , 0.11111111],
       [1.        , 0.44444444, 0.11111111, 0.        ]])

In [86]:
weighted_matrix(7)

array([[0.        , 0.02777778, 0.11111111, 0.25      , 0.44444444,
        0.69444444, 1.        ],
       [0.02777778, 0.        , 0.02777778, 0.11111111, 0.25      ,
        0.44444444, 0.69444444],
       [0.11111111, 0.02777778, 0.        , 0.02777778, 0.11111111,
        0.25      , 0.44444444],
       [0.25      , 0.11111111, 0.02777778, 0.        , 0.02777778,
        0.11111111, 0.25      ],
       [0.44444444, 0.25      , 0.11111111, 0.02777778, 0.        ,
        0.02777778, 0.11111111],
       [0.69444444, 0.44444444, 0.25      , 0.11111111, 0.02777778,
        0.        , 0.02777778],
       [1.        , 0.69444444, 0.44444444, 0.25      , 0.11111111,
        0.02777778, 0.        ]])

## Prevalence

In [104]:
M = np.array([[28,7,6],[7,16,4],[6,4,22]])
M

array([[28,  7,  6],
       [ 7, 16,  4],
       [ 6,  4, 22]])

In [114]:
M = np.array([[72,5],[5,18]])
M

array([[72,  5],
       [ 5, 18]])

In [115]:
prev_list = []

for i in range(len(M) - 1):
    for j in range(i+1, len(M)):
        prev_list.append(abs(M[i][i] - M[j][j]))

prev = np.sum(prev_list)
prev / (100 * len(M) * (len(M)-1) / 2)

0.54

In [110]:
prev

36

In [111]:
len(M)

2