In [2]:
import joblib
import matplotlib.pyplot as plt
from quadratic_weighted_kappa_edit import quadratic_weighted_kappa, onehalf_weighted_kappa, confusion_matrix, weighted_matrix, onehalf_weighted_matrix, linear_weighted_kappa, kappa
import numpy as np
from sklearn.metrics import cohen_kappa_score

c:\users\20167947\appdata\local\programs\python\python38\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
def weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            weighted[i][j] = float(((i-j)**2)/(N-1)**2) 
    return weighted

weighted_matrix(3)

array([[0.  , 0.25, 1.  ],
       [0.25, 0.  , 0.25],
       [1.  , 0.25, 0.  ]])

In [1]:
quadratic_weighted_kappa([1,2,3,3],[2,1,3,3])

NameError: name 'quadratic_weighted_kappa' is not defined

In [4]:
quadratic_weighted_kappa([4,5,6,6],[5,4,6,6])

Quadratic


0.6363636363636364

In [12]:
A = [1,2,3]
B = [2,1,3]

In [6]:
def linear_weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            weighted[i][j] = float((abs(i-j))/(N-1)) 
    return weighted

In [9]:
l = linear_weighted_matrix(6)

In [11]:
import pandas as pd

df = pd.DataFrame (l)

## save to xlsx file

filepath = 'w.xlsx'

df.to_excel(filepath, index=False)

In [3]:
linear_weighted_kappa(A,B)

Linear weight
[[0.  0.5 1. ]
 [0.5 0.  0.5]
 [1.  0.5 0. ]]


0.25

In [13]:
from sklearn.metrics import cohen_kappa_score
cohen_kappa_score(A,B, weights="linear")

0.25

In [7]:
from sklearn.metrics import confusion_matrix
C = confusion_matrix(A,B)
C

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int64)

In [8]:
N=3
A_hist=np.zeros([N])
for item in A: 
    A_hist[item - 1]+=1
    
B_hist=np.zeros([N])
for item in B: 
    B_hist[item - 1]+=1
    

print(f'Actuals value counts:{A_hist}, \nPrediction value counts:{B_hist}')

Actuals value counts:[1. 1. 1.], 
Prediction value counts:[1. 1. 1.]


In [9]:
E = np.outer(A_hist, B_hist)/3
E

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [10]:
w = weighted_matrix(3)
w

array([[0.  , 0.25, 1.  ],
       [0.25, 0.  , 0.25],
       [1.  , 0.25, 0.  ]])

In [11]:
num = np.sum(w * C)
num

0.5

In [12]:
denum = np.sum(w * E)
denum

0.9999999999999999

In [13]:
k = 1 - (num / denum)
k

0.4999999999999999

In [14]:
quadratic_weighted_kappa(A,B)

Quadratic


0.5

In [15]:
a = np.array(A).reshape(-1,1).transpose()
b = np.array(B).reshape(-1,1).transpose()
c = np.concatenate((a,b), axis=0)
c.shape

(2, 3)

In [16]:
c

array([[1, 2, 3],
       [2, 1, 3]])

In [17]:
# TESTING
x = np.array([0,4,0]).reshape(1,-1)
y = np.array([0,4,0]).reshape(1,-1)
z = np.array([0,1,3]).reshape(1,-1)

xyz = np.concatenate((x,y,z), axis=0)
xyz

array([[0, 4, 0],
       [0, 4, 0],
       [0, 1, 3]])

In [18]:
from statsmodels.stats.inter_rater import fleiss_kappa
fleiss_kappa(xyz)

0.5555555555555557

In [19]:
import krippendorff

xy = np.concatenate((x,y), axis=0)

kappa = krippendorff.alpha(xyz)
kappa

0.3846153846153846

In [20]:
contentA = ''
for a in A:
    contentA = contentA + str(a) + ','
contentA[:-1]

with open("rater_A.txt", "w") as f:
        f.write(contentA[:-1])    

In [21]:
contentB = ''
for b in B:
    contentB = contentB + str(b) + ','
contentB[:-1]

with open("rater_B.txt", "w") as f:
        f.write(contentB[:-1])

## Examples of problem

In [22]:
A = [1,8,10]
B = [4,5,10]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

A = [1,8,10]
B = [4,4,10]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

Quadratic
0.7244897959183674 Accepted
Quadratic
0.6376811594202898 Rejected


In [23]:
# A = [1,8,10]
# B = [4,5,10]
A = [1,2,3,4]
B = [2,1,3,4]
qwk = onehalf_weighted_kappa(A,B)
print(qwk)
#print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

# A = [1,8,10]
# B = [4,4,10]
A = [1,2,3,4]
B = [2,1,3,4]
qwk = onehalf_weighted_kappa(A,B)
print(qwk)

#print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

One-half
0.7112540190984371
One-half
0.7112540190984371


In [24]:
A = [2,8,9,4,9]
B = [2,5,8,7,8]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

A = [9,8,9,4,2]
B = [9,4,8,7,1]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

Quadratic
0.7058823529411764 Accepted
Quadratic
0.6853146853146852 Rejected


In [25]:
A = [2,8,5,8,12]
B = [1,8,5,2,12]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

A = [2,8,5,9,12]
B = [1,8,5,2,12]
qwk = quadratic_weighted_kappa(A,B)

print(qwk, "Accepted" if qwk >= 0.7 else "Rejected")

Quadratic
0.7482993197278911 Accepted
Quadratic
0.6727748691099475 Rejected


In [26]:
w = weighted_matrix(4)
w

array([[0.        , 0.11111111, 0.44444444, 1.        ],
       [0.11111111, 0.        , 0.11111111, 0.44444444],
       [0.44444444, 0.11111111, 0.        , 0.11111111],
       [1.        , 0.44444444, 0.11111111, 0.        ]])

In [27]:
def new_weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            print(i, j)
            #if i - j >= 0:
            weighted[i][j] = float(((i-j)**1.5)/(N-1)**1.5) 
    return weighted

In [28]:
#new_weighted_matrix(3)

In [16]:
# TESTING
x = np.array([1,2,1,1,2,2]).reshape(1,-1)
y = np.array([2,1,1,1,2,2]).reshape(1,-1)

xy = np.concatenate((x,y), axis=0)
xy

array([[1, 2, 1, 1, 2, 2],
       [2, 1, 1, 1, 2, 2]])

In [17]:
import krippendorff

kappa = krippendorff.alpha(xy)
kappa

0.38888888888888895

In [18]:
from pyagree import bangdiwala_b, cohen_kappa, scott_pi, yule_y

In [19]:
A = [[10,  1],[ 5, 10]]

In [20]:
bangdiwala_b(A)

0.6060606060606061

In [21]:
cohen_kappa(A)

0.5491329479768786

In [22]:
A = [[1,8,10],[4,5,10],[6,7,8]]
A

[[1, 8, 10], [4, 5, 10], [6, 7, 8]]

In [23]:
A = np.matrix(A)
A

matrix([[ 1,  8, 10],
        [ 4,  5, 10],
        [ 6,  7,  8]])

In [28]:
scott_pi(A)

-0.16677653263019107

In [25]:
bangdiwala_b(A)

0.07646559048428207

In [26]:
cohen_kappa(A)

-0.15234374999999994

In [39]:
A = [[0,1],[2,3],[4,5]]
A = np.matrix(A)

In [5]:
cohen_kappa(A)

-0.15234374999999994

In [41]:
A = [1,2,3]
B = [2,1,3]
qwk = onehalf_weighted_kappa(A,B)
print(qwk)

One-half
0.3786796564403574


In [42]:
A = [2, 8 ,5, 9, 12]
B = [1, 8, 5, 2, 12]
qwk = onehalf_weighted_kappa(A,B)
print(qwk)

One-half
0.6585116780652461


In [43]:
def weighted_matrix_1(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            weighted[i][j] = float((abs(i-j)**1)/(N-1)**1) 
    return weighted

In [44]:
weighted_matrix_1(4)

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [0.33333333, 0.        , 0.33333333, 0.66666667],
       [0.66666667, 0.33333333, 0.        , 0.33333333],
       [1.        , 0.66666667, 0.33333333, 0.        ]])

In [45]:
weighted_matrix_1(4)

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [0.33333333, 0.        , 0.33333333, 0.66666667],
       [0.66666667, 0.33333333, 0.        , 0.33333333],
       [1.        , 0.66666667, 0.33333333, 0.        ]])

In [46]:
weighted_matrix_1(3)

array([[0. , 0.5, 1. ],
       [0.5, 0. , 0.5],
       [1. , 0.5, 0. ]])

In [47]:
A = [1,2,3]
B = [2,1,3]
linear_weighted_kappa(A,B)

Linear weight


0.25

In [48]:
quadratic_weighted_kappa(A,B)

Quadratic


0.5

In [49]:
onehalf_weighted_kappa(A,B)

One-half


0.3786796564403574

In [50]:
cohen_kappa_score(A,B)

0.0

In [51]:
quadratic_weighted_kappa([1,2,3],[1,2,3])

Quadratic


1.0

In [52]:
weighted_matrix(3)

array([[0.  , 0.25, 1.  ],
       [0.25, 0.  , 0.25],
       [1.  , 0.25, 0.  ]])

In [3]:
r1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]
r2 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 2, 2, 3, 1, 1, 1, 3, 3]

In [4]:
quadratic_weighted_kappa(r1,r2)

Quadratic
[[0.   0.25 1.  ]
 [0.25 0.   0.25]
 [1.   0.25 0.  ]]


0.275023386342376

In [6]:
weighted_matrix(5)

array([[0.    , 0.0625, 0.25  , 0.5625, 1.    ],
       [0.0625, 0.    , 0.0625, 0.25  , 0.5625],
       [0.25  , 0.0625, 0.    , 0.0625, 0.25  ],
       [0.5625, 0.25  , 0.0625, 0.    , 0.0625],
       [1.    , 0.5625, 0.25  , 0.0625, 0.    ]])

# Test

In [14]:
A = [1,2,3]
B = [2,1,3]

cohen_kappa_score(A, B, weights='quadratic')

0.4999999999999999

In [15]:
cohen_kappa_score(A,B)

0.0

In [16]:
cohen_kappa_score(A, B, weights='linear')

0.25

### Tanpa parameter labels

In [22]:
C = [1,2,4]
D = [2,1,4]

cohen_kappa_score(C, D, weights='quadratic')

0.4999999999999999

### Penting untuk menggunakan parameter labels

In [21]:
C = [1,2,4]
D = [2,1,4]

cohen_kappa_score(C, D, labels=[1,2,3,4], weights='quadratic')

0.7857142857142857

In [18]:
cohen_kappa_score(C,D)

0.0

In [19]:
cohen_kappa_score(C, D, weights='linear')

0.25

In [20]:
quadratic_weighted_kappa(A,B)

Quadratic
[[0.   0.25 1.  ]
 [0.25 0.   0.25]
 [1.   0.25 0.  ]]


0.5

In [5]:
quadratic_weighted_kappa(C,D)

Quadratic
[[0.         0.11111111 0.44444444 1.        ]
 [0.11111111 0.         0.11111111 0.44444444]
 [0.44444444 0.11111111 0.         0.11111111]
 [1.         0.44444444 0.11111111 0.        ]]


0.7857142857142857

In [13]:
linear_weighted_kappa(A,B)

Linear weight


0.25

In [14]:
linear_weighted_kappa(C,D)

Linear weight


0.5

In [16]:
kappa(A,B)

1.1102230246251565e-16

In [17]:
kappa(C,D)

1.1102230246251565e-16

In [26]:
A = [1,2,5,4,7,8]
B = [2,1,5,4,8,7]

cohen_kappa_score(A,B, labels=[1,2,3,4,5,6,7,8], weights='linear')

0.7647058823529411

In [24]:
linear_weighted_kappa(A,B)

Linear weight
[[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
  0.85714286 1.        ]
 [0.14285714 0.         0.14285714 0.28571429 0.42857143 0.57142857
  0.71428571 0.85714286]
 [0.28571429 0.14285714 0.         0.14285714 0.28571429 0.42857143
  0.57142857 0.71428571]
 [0.42857143 0.28571429 0.14285714 0.         0.14285714 0.28571429
  0.42857143 0.57142857]
 [0.57142857 0.42857143 0.28571429 0.14285714 0.         0.14285714
  0.28571429 0.42857143]
 [0.71428571 0.57142857 0.42857143 0.28571429 0.14285714 0.
  0.14285714 0.28571429]
 [0.85714286 0.71428571 0.57142857 0.42857143 0.28571429 0.14285714
  0.         0.14285714]
 [1.         0.85714286 0.71428571 0.57142857 0.42857143 0.28571429
  0.14285714 0.        ]]


0.7647058823529411

In [7]:
def weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            weighted[i][j] = 1 - ( float(((i-j)**2)/(N-1)**2) )
            #weighted[i][j] = 1 - ( float((abs(i-j))/(N-1)) )
    return weighted

w = weighted_matrix(4)
w

array([[1.        , 0.88888889, 0.55555556, 0.        ],
       [0.88888889, 1.        , 0.88888889, 0.55555556],
       [0.55555556, 0.88888889, 1.        , 0.88888889],
       [0.        , 0.55555556, 0.88888889, 1.        ]])

In [8]:
def weighted_matrix(N):
    weighted = np.zeros((N,N)) 
    for i in range(len(weighted)):
        for j in range(len(weighted)):
            #weighted[i][j] = 1 - ( float(((i-j)**2)/(N-1)**2) )
            weighted[i][j] = 1 - ( float((abs(i-j))/(N-1)) )
    return weighted

w = weighted_matrix(4)
w

array([[1.        , 0.66666667, 0.33333333, 0.        ],
       [0.66666667, 1.        , 0.66666667, 0.33333333],
       [0.33333333, 0.66666667, 1.        , 0.66666667],
       [0.        , 0.33333333, 0.66666667, 1.        ]])

In [38]:
import pandas as pd

df = pd.DataFrame (w)

## save to xlsx file

filepath = 'w.xlsx'

df.to_excel(filepath, index=False)